version: "3.9"
services:
    nginx:
        image: "nginx:alpine"
        restart: always
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    php-fpm:
        build: php-fpm
        restart: always
        working_dir: /app
        volumes:
            - ".:/app"
            - "./php-fpm/php-overrides.ini:/usr/local/etc/php/conf/666-overrides.ini"





